;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Pipeline]
Pos=0,31
Size=1850,547
Collapsed=0
DockId=0x00000001,0

[Window][View]
Pos=0,580
Size=806,403
Collapsed=0
DockId=0x00000003,0

[Window][Logger]
Pos=808,580
Size=1042,403
Collapsed=0
DockId=0x00000004,0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][StatusBar]
Pos=0,981
Size=1850,43
Collapsed=0

[Window][node_path]
Pos=625,312
Size=779,400
Collapsed=0

[Table][0x85F179F5,3]
RefScale=25
Column 0  Sort=0v

[Table][0xE72C92BC,2]
RefScale=25
Column 0  Width=125
Column 1  Weight=1.0000

[Docking][Data]
DockSpace     ID=0xAFC85805 Window=0x079D3A04 Pos=0,31 Size=1850,952 Split=Y
  DockNode    ID=0x00000001 Parent=0xAFC85805 SizeRef=1480,547 CentralNode=1 Selected=0xA91A932C
  DockNode    ID=0x00000002 Parent=0xAFC85805 SizeRef=1480,403 Split=X
    DockNode  ID=0x00000003 Parent=0x00000002 SizeRef=806,298 Selected=0xCD8A0BD6
    DockNode  ID=0x00000004 Parent=0x00000002 SizeRef=1042,298 Selected=0x9DD4E196

;;;<<<Layout_655921752_Default>>>;;;
[Visibility]
221744210_View=true
2791942160_Pipeline=true
2960180848_Logger=true
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=true
ShowFps=false
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{"BottomSpace":3,"LoggerSpace":4,"MainDockSpace":2949142533}}
